### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by james2540** [snsdosen/NibbleSokoban#1]
When I click either verify or upload it says expected identifier before '{' token What do I do?

**Comment by snsdosen** [comment]
Hm. That doesn't give me much to go on.
What OS are you using? Have you configured Arduino for Nibble properly? How did you download the source? If the folder contains a "-main" sufix you need to remove it. And do you just want to play the game? If that's the case you can just download compiled binary.

**Comment by james2540** [comment]
What is OS and yes I think I have configured it correctly An I downloaded it by clicking the green code down button and downloading zip, no it didn't contain a "-main" sufix that I could see and yes I just want to play the game thanks for the help.

**Comment by james2540** [comment]
How do I upload compiled binary?

**Comment by snsdosen** [comment]
OS is an operating system. If you are using Windows you can follow the guide from the readme for binary flashing.

**Comment by james2540** [comment]
How do I get to the guide?

**Comment by snsdosen** [comment]
Here is the guide on the main page:
https://github.com/snsdosen/NibbleSokoban#flashing-compiled-binary-windows-only

And the binaries can be downloaded here:
https://github.com/snsdosen/NibbleSokoban/releases

Just download the latest .bin file (1.1 version at this moment).

**Comment by james2540** [comment]
ok thanks a lot
