### ISSUE TITLE
There is a problem in the slots code.

### ISSUE THREAD

**Issue by james2540** [snsdosen/NibbleSokoban#2]
When I press verify or upload it brings up a message saying: 'EEPROM' was not declared in this scope, what does it mean and what do I do?

**Comment by snsdosen** [comment]
I believe your programming environment is not configured properly.

Take a look at my video:
https://youtu.be/bPpZYpI3DF8

Follow it from 2 minute mark.
It's in croatian but you can use english subtitles.
It will show you how to set up everything properly

**Comment by james2540** [comment]
Thanks

**Comment by james2540** [comment]
Does the version of Arduino that I use have to be version 1.8.13?

**Comment by snsdosen** [comment]
There is no need to aim for the specific version, always use the latest one

**Comment by james2540** [comment]
Ok thanks
